document.getElementById('khodamForm').addEventListener('submit', function (event) {
    event.preventDefault();

    var name = document.getElementById('name').value;
    var birthdate = document.getElementById('birthdate').value;

    var khodamResult = calculateKhodam(name, birthdate);

    document.getElementById('khodamResult').textContent = khodamResult;
    document.getElementById('result').classList.remove('hidden');
});

function calculateKhodam(name, birthdate) {
    // Logika sederhana untuk menentukan khodam
    // Logika ini hanya contoh dan tidak memiliki dasar ilmiah atau spiritual

    var khodams = [
        "Macan Pemarah",
        "Buaya Sunda",
        "Beruang Sunda",
        "Harimau Birahi",
        "Tutup Odol",
        "Tutup Panci",
        "Kaleng Kejepit",
        "Kanebo Kering",
        "Kapal Karam",
        "Gergaji Mesin",
        "Nyi Blorong",
        "Jin Rawa Rontek",
        "Kucing Israel",
        "Capung Gila",
        "Tumis Kangkung",
        "Jam Dinding Rusak",
        "Gunting Tumpul",
        "Kasur Empuk",
        "Payung Robek",
        "Kulkas Kosong",
        "Piring Pecah",
        "Meja Berdecit",
        "Koper Berat",
        "Topi Melorot",
        "Lem Super Lengket",
        "Keripik Garing",
        "Senter Mati",
        "Kue Kering",
        "Bantal Empuk",
        "Kendi Air",
        "Penggaris Melengkung",
        "Tali Jemuran",
        "Kancut Badak",
        "Rayap Gendut",
        "Pagar Besi",
        "Kunci Gembok",
        "LC Karaoke",
        "Cicak Kawin",
        "Cupang Betina",
        "Sundel Bolong",
        "Tuyul Kesandung",
        "Genderuwo TikTok",
        "Jin Susu Kental Manis",
        "Si Lontong Lumer",
        "Setan Payung Bocor",
        "Jin Es Krim Leleh",
        "Pocong Bersepeda",
        "Kuntilanak Selfie",
        "Tuyul Main PS5",
        "Batu Bata",
        "Remote TV",
        "Kompor Meledak",
        "Helm Nyasar",
        "Gitar Putus Senar",
        "Si Sate Klathak",
        "Genderuwo Tertawa",
        "Jin Penjual Cilok",
        "Setan Jualan Online",
        "Kuntilanak Kecanduan Kopi",
        "Pocong Nyanyi Dangdut",
        "Jin Martabak Telor",
        "Tuyul Kerja Part-Time",
        "Handuk Basah",
        "Kipas Rusak",
        "Jemuran Penuh",
        "Tisu Gulung",
        "Gelas Plastik",
        "Si Bakso Urat",
        "Setan Suka Drama Korea",
        "Genderuwo Nonton Netflix",
        "Jin Donat Kentang",
        "Kuntilanak Pake Kacamata",
        "Pocong Mainan Kucing",
        "Jin Peminum Boba",
        "Tuyul Bersepatu Roda",
        "Si Keripik Pedas",
        "Setan Kolektor Komik",
        "Genderuwo Pemain Basket",
        "Jin Sate Madura",
        "Kuntilanak Nge-Gym",
        "Pocong Ngantor",
        "Tuyul Jago Coding",
        "Si Pizza Keju",
        "Setan Pemilik Cafe",
        "Genderuwo Seniman",
        "Jin Coklat Batangan",
        "Kuntilanak Hobi Makeup",
        "Pocong Main TikTok",
        "Tuyul Kuliah Online",
        "Si Rambutan Manis",
        "Sendal Jepit",
        "Panci Gosong",
        "Guling Gembung",
        "Sarung Bantal",
        "Kaos Oblong",
        "Jin Kipas Angin",
        "Setan Pembeli Pulsa",
        "Kuntilanak Karaoke",
        "Pocong Joget",
        "Ember Bocor",
        "Celana Sobek",
        "Sepeda Tua",
        "Telepon Jadul",
        "Tas Plastik",
        "Kalender Bekas",
        "Pensil Inul",
        "Buku Kusut",
        "Korek Macet",
        "Mangkok Retak",
        "Lemari Penuh"
    ];



    var index = (name.length + new Date(birthdate).getDay()) % khodams.length;
    return khodams[index];
}
